// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOfN98CGVXFAt4ubSNEVnKMB9IENUPdOI',
    appId: '1:449303944501:web:374ab58807ca72327e007c',
    messagingSenderId: '449303944501',
    projectId: 'focusbuddy-ai-2026',
    authDomain: 'focusbuddy-ai-2026.firebaseapp.com',
    storageBucket: 'focusbuddy-ai-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPgFVDyznIo6WgyeiAlqSt28cEcesO38E',
    appId: '1:449303944501:android:2ccb56cd93824b5e7e007c',
    messagingSenderId: '449303944501',
    projectId: 'focusbuddy-ai-2026',
    storageBucket: 'focusbuddy-ai-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxncEDy-uAIpBOPjOt-RLjeS-DSdUrV0o',
    appId: '1:449303944501:ios:c7b46378d45c02bb7e007c',
    messagingSenderId: '449303944501',
    projectId: 'focusbuddy-ai-2026',
    storageBucket: 'focusbuddy-ai-2026.firebasestorage.app',
    iosBundleId: 'com.example.focusbuddyAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxncEDy-uAIpBOPjOt-RLjeS-DSdUrV0o',
    appId: '1:449303944501:ios:c7b46378d45c02bb7e007c',
    messagingSenderId: '449303944501',
    projectId: 'focusbuddy-ai-2026',
    storageBucket: 'focusbuddy-ai-2026.firebasestorage.app',
    iosBundleId: 'com.example.focusbuddyAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOfN98CGVXFAt4ubSNEVnKMB9IENUPdOI',
    appId: '1:449303944501:web:11cbfadcc8b6d74c7e007c',
    messagingSenderId: '449303944501',
    projectId: 'focusbuddy-ai-2026',
    authDomain: 'focusbuddy-ai-2026.firebaseapp.com',
    storageBucket: 'focusbuddy-ai-2026.firebasestorage.app',
  );
}
